export { default as ContentBanner } from './ContentItem/ContentBanner';
export { default as SpeechTypeLabel } from './SpeechTypeLabel/SpeechTypeLabel';
export { default as EditOrAddCatalog } from './EditOrAddCatalog/EditOrAddCatalog';
export { default as AddOrEditLastCatalog } from './EditOrAddLastCatalog/EditOrAddLastCatalog';
export { default as ConfirmModal } from './ConfirmModal/ConfirmModal';
export { default as UploadImg } from './UploadImg/UploadImg';
export { default as UploadFile } from './UploadFile/UploadFile';
export { default as SyncSpeech } from './SyncSpeech/SyncSpeech';
export { default as SpeechModal } from './SpeechModal/SpeechModal';
